### ISSUE TITLE
这代码啥情况？edge_connect不要训练吗？测试的代码呢？

### ISSUE THREAD

**Issue by jianhaogao** [wds1998/Edge-LBAM#1]

**Comment by wds1998** [comment]
We have released the test code, the training code of edgeconnect you can refer to https://github.com/knazeri/edge-connect, use canny edge for training, and finally use the result of MECNet joint training with the main network.

**Comment by wds1998** [comment]
> _No description provided._

We have released the test code, the training code of edgeconnect you can refer to https://github.com/knazeri/edge-connect, use canny edge for training, and finally use the result of MECNet joint training with the main network.
