### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'config.yml'

### ISSUE THREAD

**Issue by asdj32n12dk** [wds1998/Edge-LBAM#3]
Hello, when I run test code I can't find config.yml..

Could you provide this config, that you used for paper?

Thanks

**Comment by wds1998** [comment]
We have provided the config.yml, you can use it for test or train by yourself.

**Comment by wds1998** [comment]
> Hello, when I run test code I can't find config.yml..
> 
> Could you provide this config, that you used for paper?
> 
> Thanks

We have provided the config.yml, you can use it for test or train by yourself.
